### ISSUE TITLE
Implement registering Runtimes in Compass Director

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/compass-manager#10]
Implement code that will register Runtime in the director.

Acceptance criteria:
- [ ] Compass Manager is able to make authorised calls to the Compass Director API
- [ ] Compass Manager registers new Runtime when Kyma CR contains a new kubeconfig
- [ ] It must be assumed that Compass may be temporarily unavailable. We must provide resilience mechanisms, and eventual consistency.  
- [ ] Compass Manager unregisters Runtime when Kyma CR is removed.

**Comment by akgalwas** [comment]
We must consider how to store `RuntimeID` returned by the Compass API to be able to unregister the Runtime at some point.

**Comment by mvshao** [comment]
**Workplan**
- [ ] Establish an authorised connection between Compass Manager and Compass Director
- [ ] Test the connection by retrieving a runtime from Director
- [ ] Implement a logic that will register new runtime in Director (re-use the core functionality from Provisioner)
- [ ] Provide resilience mechanisms for queries executed to Director

**Blocked**
- [ ] Implement a logic that will unregister runtime from Director (blocked by #9)

**Comment by mvshao** [comment]
We also need to have in mind that we must implement `SetRuntimeStatusCondition()` to mark the runtime in Director as `Connected` (now the status is permanent in `Initial` state)

**Comment by mvshao** [comment]
Workplan
- [x] registration of the Runtime in Compass Director https://github.com/kyma-project/compass-manager/pull/18
- [ ] Compass Manager creates an `CompassMapping` CR + Whitesource https://github.com/kyma-project/compass-manager/pull/27
- [ ] Compass Manager should mark the runtime in Director as `Connected`
- [ ] deregistration of the Runtime while `Kyma` CR was deleted
- [ ] `CompassMapping` CR custom statuses and finalizers
- [ ] RBAC for `CompassMapping` CR, align with SRE

**Comment by akgalwas** [comment]
**High level requirements**

The operator must be able to operate in the following conditions:
- Provisioner is not responsible for Compass integration (target architecture)
- Provisioner registers runtime, and Compass Manager creates CRA's secret (intermediary architecture)
- Runtime is removed, and recreated (trial suspension scenario)

The following requirements must be met:
1. If the Application Connector module is disabled, the event is filtered out.
2. If the Application Connector module is enabled, there are two options:
  - If runtime is not registered yet, operator performs the following operations:
    - Registers runtime
    - Fetches one-time token from the Compass Director
    - Creates config secret for the Compass Runtime Agent
    - Stores information in the KCP cluster determining if the runtime is registered 
  - If runtime is already registered, operator performs the following actions:
    - Fetches one-time token from the Compass Director. 
    - Updates config secret for the Compass Runtime Agent

**Comment by akgalwas** [comment]
Compass Manager will retry operations in case of failures. `Compass Manager Mapping` must contain [status information](https://github.com/kyma-project/infrastructure-manager/blob/0d22ae07324e71670cd43b37ecd4c88d3a4b4d21/api/v1/gardenercluster_types.go#L77) to improve observability. 

The following requirements must be met:
- If the Compass Manager failed to register runtime the CR must have `failed` status.
- If the Compass Manager successfully registered runtime the CR must contain `kyma-project.io/compass-runtime-id` annotation. 
- If the Compass Manager failed to create secret CR must set `failed` status. 

It would give better insight into the system, and allow to see:
- When runtime was registered, and configuration secret created.
- The failure rate of Compass operations.

**Comment by mvshao** [comment]
Done, the core flow (registering, unregistering) creatin CompassMapping, statuses and finalizers are implemented.
