### ISSUE TITLE
Increase Compass Manager memory

### ISSUE THREAD

**Issue by VOID404** [kyma-project/compass-manager#132]
**Description**

We should increase Compass Manager memory limit to at least 256MB. 
512MB might be needed if we want to handle 10 000 Kymas.

**Reasons**

Stress test showed Compass Manager crashing under heavier load. Increasing memory limit fixed the issue

**Attachments**

Stress test results: https://secret.link/framefrog/compass-manager-spammer/blob/main/results%2Fv20240220-c6bbeb1d.md

**Comment by mvshao** [comment]
Closing this as done. Compass Manager on environments is configured with increased memory limits.
