### ISSUE TITLE
Impossible to sync and add application through BTP

### ISSUE THREAD

**Issue by Disper** [kyma-project/compass-manager#150]
**Description**

**Expected result**
`global_subaccount_id`  label should be used.

**Actual result**
`global_account_id` label is used.

**Steps to reproduce**
TBD

**Troubleshooting**
TBD

**TODO**
- [x] https://github.com/kyma-project/compass-manager/pull/151
- [x] bump
- [x] release

**Comment by mvshao** [comment]
Compass Manager with fix was released
