### ISSUE TITLE
Compass Manager - Prepare migration script/Go program that will set `compass-runtime-id-for-migration` annotation on Kyma resources

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/compass-manager#31]
**Description**
Prepare a Go program/script that will iterate over Kyma resources. For each Kyma resource it will:

1. Read `runtime-id` label from the Kyma resource
2. Set `compass-runtime-id-for-migration` annotation with value for `runtime-id` label

**Reasons**

In order to migrate to the architecture with the Compass Manager responsible Compass Integration some additional steps must be performed. Before Compass Manager will be deployed on the target environment there will be a need to modify existent Kyma resources. The migration script is needed to make sure Compass Manager will not attempt to register runtimes that are already registered.

**Comment by tobiscr** [comment]
Obsolete - closing it.
