### ISSUE TITLE
Migrate old runtimes that are connected to the Compass and don't have App Conn module enabled

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/compass-manager#87]
**Description**

As pre-requisite for the rollout of the Compass Manager to KCP STAGE and PROD is the preparation and execution of this migration step mandatory.

Migrate old runtime which are already registered at the Compass Director and create compass mapping for it.

AC:
- [x] Implement migration logic
- [x] Inform @zhoujing2022 about the date when the migration for 
    - [x] KCP STAGE will be completed
    - [x] KCP PROD will be completed

**Comment by koala7659** [comment]
Repo with Application to create missing Compass mappings for runtimes: 

https://github.tools.sap/framefrog/cm-kyma-migrator/

**Comment by Disper** [comment]
@koala7659 investigating too many reconciliation messages
