### ISSUE TITLE
Adjust CMP Director URL on KCP DEV (deadline: 12th Jan 2024)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/compass-manager#91]
**Description**

CMP system used for registering applications on KCP DEV will be replaced by a new system until 12th Jan 2024 which has a new URL.

AC:
- [ ] Verify the secret generated by the Provisioner (used by the Application Connector) and ensure that the value of existing secrets gets updated (if an update is required)
    - [ ] Implement the migration logic for the application connector to work after the CMP URL update
- [ ] Update the Compass Manager on DEV to use the new CMP system URL: [compass-gateway-auth-oauth.cmp-main.dev](http://compass-gateway-auth-oauth.cmp-main.dev/).kyma.cloud.sap
- [ ] Ping Nikolay Y. to create IntegrationSystem/s and to issue credentials for us (see SlackURL in the issue field "external link")

**Expected result**

KCP DEV is using the new CMP system URL.

**Actual result**

We use the old CMP system URL on KCP DEV which will be replaced until 12th Jan 2024.

**Steps to reproduce**

Verify configuration of Compass client on KCP DEV.

**Troubleshooting**

**Comment by mvshao** [comment]
**Workplan**
- [ ] Update the default URL value in Compass Manager and Provisioner
- [ ] Make necessary changes in code in Compass Manager and Provisioner
- [ ] Ask SRE to create a new secret named e.g. `kcp-provisioner-new-credentials-file` that contains Compass auth data
- [ ] Update the ArgoCD charts for Compass Manager and Provisioner

**Comment by nyordanoff** [comment]
Hello,

As we have agreed in the slack thread discussion, the changes are released from CMP side and the new URL is accessible.
